### ISSUE TITLE
Support for Tabs

### ISSUE THREAD

**Issue by apratheek** [mutohq/Fabrica#16]
Require support for Bootstrap/Semantic UI type tabs
###### Inspiration
1. [Semantic UI](http://semantic-ui.com/modules/tab.html)
2. [Bootstrap](http://getbootstrap.com/javascript/#tabs)
###### Goals
1. [x] Vanilla JS tabs

**Comment by nrshubham** [comment]
Added Tabs support in latest commit "ca5ecd8"
