### ISSUE TITLE
Progress Bars

### ISSUE THREAD

**Issue by apratheek** [mutohq/Fabrica#22]
Require animated/non-animated progress bars
###### Inspiration
1. [ ] - [Bootstrap](http://getbootstrap.com/components/#progress)
###### Goals
1. [x] - Progress bar with vanilla JS animations

**Comment by apratheek** [comment]
@Prabhnith, @nrshubham could we add a striped (or throw in any other idea here) progress bar, just like how Bootstrap does it?

**Comment by nrshubham** [comment]
Added in latest commit
